defaultEntryPoints = ["websecure"]
logLevel = "DEBUG"

[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    defaultRule = "Host(`localhost`)"
    watch = true
    exposedByDefault = false

  [providers.file]
    directory = "/certs"
    watch = true

[accessLog]

[api]
  dashboard = true

[entryPoints]
  [entryPoints.web]
    address = ":80"

    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"

  [entryPoints.websecure]
    address = ":443"
